export const ENV = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000",
  IMPACT_BASE_URL: process.env.NEXT_PUBLIC_IMPACT_BASE_URL ?? "http://localhost:8001",
  FARMER_IMPACT_BASE_URL: process.env.NEXT_PUBLIC_FARMER_IMPACT_BASE_URL ?? "http://localhost:8003",
  MAPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN ?? "",
  KNOWLEDGE_HUB_URL: process.env.NEXT_PUBLIC_KNOWLEDGE_HUB_URL ?? "",
  SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN ?? "",
  ENVIRONMENT: process.env.NEXT_PUBLIC_ENVIRONMENT ?? "development",
  RECAPTCHA_ENABLED: process.env.NEXT_PUBLIC_RECAPTCHA_ENABLED === "true",
  RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? "",
  RECAPTCHA_BASE_URL: process.env.NEXT_PUBLIC_RECAPTCHA_BASE_URL ?? "",
  PAYSTACK_PUBLIC_KEY: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY ?? "",
} as const;
